language: node_js
node_js: 12

before_script: 
  - cd server-nest
before_install: 
  - cd server-nest
  - npm i -g npm@latest

install:
  - npm install
  - npm run build

jobs:
  include:
    - state: "Test"
  name: "Unit Test Node 12"
  script: npm test
  node_js: 12
  after_success: npm run coverage