language: node_js

cache:
  directories:
    - "node_modules"

before_script: 
  - cd server-nest
before_install: 
  - npm i -g npm@latest

install:
  - npm run start:dev

jobs:
  include:
    - state: "Test"
  name: "Unit Test Node 12"
  script: npm test
  node_js: 12
  after_success: npm run coverage