// Generated by https://quicktype.io

export interface User {
    userId: string;
    username: string;
    password: string;
    name: Name;
    email: string;
}

export interface Name {
    first: string;
    last: string;
}
